### ISSUE TITLE
What is the License of the library?

### ISSUE THREAD

**Issue by ChristopheMaldivi** [dwfox/DWRulerView#2]
Hi,

First I would like to thank you for your work. Your library is useful and I I'll use it in one of my applications.
However there is an issue: What is the license of the library? I need to know the license to be sure I can use it.

NB: you can easily add a LICENSE file of your choice when adding a file through github UI.

Thanks a lot for your help, best regards,

Christophe

**Comment by dwfox** [comment]
This source code is MIT License and added license file on this project.

**Comment by ChristopheMaldivi** [comment]
Thanks a lot for your help, much appreciated :)
